/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        Vehicle vehicle1 = new Vehicle("Alex", "Toyota");
        Vehicle vehicle2 = new Vehicle("Connie", "Audi");

        vehicle1.speedUp(30);
        vehicle2.speedUp(50);

        System.out.println(new App().getGreeting());
    }
}

class Vehicle{

    private String name;
    private String brand;

    Vehicle(String name, String brand){
        this.name = name;
        this.brand = brand;
    }

    public void speedUp(int speed){
        System.out.println("Name: " + this.name + ", Brand: " + this.brand + ", speed up to "+ speed + "km/hr.");
    }

}