/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        Vehicle vehicle1 = new Vehicle("Alex", "Toyota");
        Vehicle vehicle2 = new Vehicle("Connie", "Audi");

        vehicle1.speedUp(30);
        vehicle2.speedUp(50);

        Car car = new Car("My Car", "Goodby");
        car.speedUp(180);
        car.speedUp(201);

        System.out.println(new App().getGreeting());
    }
}

class Car extends Vehicle{

    Car(String name, String brand) {
        super(name, brand);
    }

    @Override
    public void speedUp(int speed) {
        if (speed <= 200){
            System.out.println("Name: " + this.name + ", Brand: " + this.brand + ", speed up to "+ speed + "km/hr.");
        } else{
            System.out.println("Name: " + this.name + ", Brand: " + this.brand + ", speed up failed!");
        }
    }
}

class Vehicle{

    String name;
    String brand;

    Vehicle(String name, String brand){
        this.name = name;
        this.brand = brand;
    }

    public void speedUp(int speed){
        System.out.println("Name: " + this.name + ", Brand: " + this.brand + ", speed up to "+ speed + "km/hr.");
    }

}